apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  namespace: demo
  labels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/version: "6.14.1"
spec:
  endpoints:
    - path: /metrics
      port: http
      interval: 15s
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo
